version: '3'

services:
  authms:
    build: 
      context: ./
      dockerfile: AuthDockerfile
    command: ./authms
    ports:
      - 8082:8082
    depends_on:
      redis:
        condition: service_healthy
    links:
      - redis 

  select:
    build: 
      context: ./
      dockerfile: SelectDockerfile
    command: ./selectms
    ports:
      - 8083:8083

  apiserver:
    build: 
      context: ./
      dockerfile: Dockerfile
    command: ./apiserver
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - redis 

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "zxc123"
      POSTGRES_DB: "adhub"
    ports:
      - 5436:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "adhub", "-U", "postgres"]
      interval: 5s
      retries: 10

  redis:
    image: redis:latest
    environment:
      - REDIS_DB=0
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 3

  prometheus:
    image: prom/prometheus
    volumes:
      - ./configs/prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  node-exporter:
    image: prom/node-exporter