// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: select.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SelectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name      string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	OwnerId   int64    `protobuf:"varint,3,opt,name=Owner_id,json=OwnerId,proto3" json:"Owner_id,omitempty"`
	Gender    string   `protobuf:"bytes,4,opt,name=Gender,proto3" json:"Gender,omitempty"`
	MinAge    int64    `protobuf:"varint,5,opt,name=Min_age,json=MinAge,proto3" json:"Min_age,omitempty"`
	MaxAge    int64    `protobuf:"varint,6,opt,name=Max_age,json=MaxAge,proto3" json:"Max_age,omitempty"`
	Interests []string `protobuf:"bytes,7,rep,name=Interests,proto3" json:"Interests,omitempty"`
	Tags      []string `protobuf:"bytes,8,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Keys      []string `protobuf:"bytes,9,rep,name=Keys,proto3" json:"Keys,omitempty"`
	Regions   []string `protobuf:"bytes,10,rep,name=Regions,proto3" json:"Regions,omitempty"`
}

func (x *SelectRequest) Reset() {
	*x = SelectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_select_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectRequest) ProtoMessage() {}

func (x *SelectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_select_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectRequest.ProtoReflect.Descriptor instead.
func (*SelectRequest) Descriptor() ([]byte, []int) {
	return file_select_proto_rawDescGZIP(), []int{0}
}

func (x *SelectRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SelectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SelectRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *SelectRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *SelectRequest) GetMinAge() int64 {
	if x != nil {
		return x.MinAge
	}
	return 0
}

func (x *SelectRequest) GetMaxAge() int64 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

func (x *SelectRequest) GetInterests() []string {
	if x != nil {
		return x.Interests
	}
	return nil
}

func (x *SelectRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SelectRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *SelectRequest) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

type SelectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *SelectResponse) Reset() {
	*x = SelectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_select_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectResponse) ProtoMessage() {}

func (x *SelectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_select_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectResponse.ProtoReflect.Descriptor instead.
func (*SelectResponse) Descriptor() ([]byte, []int) {
	return file_select_proto_rawDescGZIP(), []int{1}
}

func (x *SelectResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SelectRequests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests  []*SelectRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	Id        int64            `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Name      string           `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	OwnerId   int64            `protobuf:"varint,4,opt,name=Owner_id,json=OwnerId,proto3" json:"Owner_id,omitempty"`
	Gender    string           `protobuf:"bytes,5,opt,name=Gender,proto3" json:"Gender,omitempty"`
	MinAge    int64            `protobuf:"varint,6,opt,name=Min_age,json=MinAge,proto3" json:"Min_age,omitempty"`
	MaxAge    int64            `protobuf:"varint,7,opt,name=Max_age,json=MaxAge,proto3" json:"Max_age,omitempty"`
	Interests []string         `protobuf:"bytes,8,rep,name=Interests,proto3" json:"Interests,omitempty"`
	Tags      []string         `protobuf:"bytes,9,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Keys      []string         `protobuf:"bytes,10,rep,name=Keys,proto3" json:"Keys,omitempty"`
	Regions   []string         `protobuf:"bytes,11,rep,name=Regions,proto3" json:"Regions,omitempty"`
}

func (x *SelectRequests) Reset() {
	*x = SelectRequests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_select_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectRequests) ProtoMessage() {}

func (x *SelectRequests) ProtoReflect() protoreflect.Message {
	mi := &file_select_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectRequests.ProtoReflect.Descriptor instead.
func (*SelectRequests) Descriptor() ([]byte, []int) {
	return file_select_proto_rawDescGZIP(), []int{2}
}

func (x *SelectRequests) GetRequests() []*SelectRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *SelectRequests) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SelectRequests) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SelectRequests) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *SelectRequests) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *SelectRequests) GetMinAge() int64 {
	if x != nil {
		return x.MinAge
	}
	return 0
}

func (x *SelectRequests) GetMaxAge() int64 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

func (x *SelectRequests) GetInterests() []string {
	if x != nil {
		return x.Interests
	}
	return nil
}

func (x *SelectRequests) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SelectRequests) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *SelectRequests) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

var File_select_proto protoreflect.FileDescriptor

var file_select_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf8, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x17,
	0x0a, 0x07, 0x4d, 0x69, 0x6e, 0x5f, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x4d, 0x69, 0x6e, 0x41, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x4d, 0x61, 0x78, 0x5f, 0x61,
	0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4d, 0x61, 0x78, 0x41, 0x67, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x18, 0x07, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x09, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x54, 0x61, 0x67, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x54, 0x61,
	0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x4b, 0x65, 0x79, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0x20, 0x0a, 0x0e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x49, 0x64, 0x22, 0xab, 0x02, 0x0a, 0x0e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x30, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x17,
	0x0a, 0x07, 0x4d, 0x69, 0x6e, 0x5f, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x4d, 0x69, 0x6e, 0x41, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x4d, 0x61, 0x78, 0x5f, 0x61,
	0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4d, 0x61, 0x78, 0x41, 0x67, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x18, 0x08, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x09, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x54, 0x61, 0x67, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x54, 0x61,
	0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x4b, 0x65, 0x79, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73,
	0x32, 0x3f, 0x0a, 0x06, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x12, 0x35, 0x0a, 0x03, 0x47, 0x65,
	0x74, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_select_proto_rawDescOnce sync.Once
	file_select_proto_rawDescData = file_select_proto_rawDesc
)

func file_select_proto_rawDescGZIP() []byte {
	file_select_proto_rawDescOnce.Do(func() {
		file_select_proto_rawDescData = protoimpl.X.CompressGZIP(file_select_proto_rawDescData)
	})
	return file_select_proto_rawDescData
}

var file_select_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_select_proto_goTypes = []interface{}{
	(*SelectRequest)(nil),  // 0: proto.SelectRequest
	(*SelectResponse)(nil), // 1: proto.SelectResponse
	(*SelectRequests)(nil), // 2: proto.SelectRequests
}
var file_select_proto_depIdxs = []int32{
	0, // 0: proto.SelectRequests.requests:type_name -> proto.SelectRequest
	2, // 1: proto.Select.Get:input_type -> proto.SelectRequests
	1, // 2: proto.Select.Get:output_type -> proto.SelectResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_select_proto_init() }
func file_select_proto_init() {
	if File_select_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_select_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_select_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_select_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectRequests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_select_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_select_proto_goTypes,
		DependencyIndexes: file_select_proto_depIdxs,
		MessageInfos:      file_select_proto_msgTypes,
	}.Build()
	File_select_proto = out.File
	file_select_proto_rawDesc = nil
	file_select_proto_goTypes = nil
	file_select_proto_depIdxs = nil
}
