bind_addr = "84.23.53.167:8080"
database_url = "user=postgres password=zxc123 host=db port=5432 dbname=adhub sslmode=disable"
log_level = "debug"
redis_addr = "redis:6379"
redis_password = "123"
redis_db = 0
file_path = "./File/Uploads"