bind_addr = ":8080"
auth_bind_addr = "authms:8082"
select_bind_addr = "select:8083"
database_url = "user=postgres password=zxc123 host=db port=5432 dbname=adhub sslmode=disable"
log_level = "debug"
redis_addr = "redis:6379"
redis_password = "123"
redis_db = 0
redis_db_ul = 1
redis_db_csrf = 2
file_path = "./File/Uploads"